# SPDX-License-Identifier: GPL-3.0-or-later
"""Build dist/CoatLink-Setup.py - the 3D-Coat installer as a single file.

    python coat_side/tools/build_standalone.py [output-path]

It takes coat_side/CoatLinkInstall.py and the files that installer copies, and
writes the same module with the payload embedded, so the result works on its own:
hand someone one file, or point 3D-Coat's own Python console at it::

    exec(open(r"...\\CoatLink-Setup.py", encoding="utf-8").read())

The payload is emitted as Python literals (repr), not as an escaped string: a
model file full of quotes and backslashes must survive the round trip byte for
byte, and that is the one encoding with no escaping rules of its own to get wrong.

Nothing about the install logic is duplicated here on purpose - the build only
adds the payload and the function that reads it, which is what keeps the single
file and the checkout behaving identically (tests/test_coatlink_install.py proves
it by installing with both and comparing the trees byte for byte).
"""

import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
COAT_SIDE = HERE.parent
ROOT = COAT_SIDE.parent
SOURCE = COAT_SIDE / "CoatLinkInstall.py"
GUARD = 'if __name__ == "__main__":'

EMBEDDED_SECTION = '''

# ---------------------------------------------------------------------------
# embedded payload - generated by coat_side/tools/build_standalone.py, digest __DIGEST__
# ---------------------------------------------------------------------------

_SCRIPTS = __SCRIPTS__

_ICONS = __ICONS__

_TOOLS_XML = __TOOLS_XML__


def read_payload():
    """The files to install, carried inside this one file."""
    return {"scripts": dict(_SCRIPTS), "icons": dict(_ICONS), "tools_xml": _TOOLS_XML}

'''


def literal(mapping):
    """A Python literal for {name: bytes} that survives any content."""
    if not mapping:
        return "{}"
    lines = ["{"]
    for name in sorted(mapping):
        lines.append("    %r: %r," % (name, mapping[name]))
    lines.append("}")
    return "\n".join(lines)


def build(output=None, payload=None, source=None):
    """Write the single-file installer; returns (path, payload digest)."""
    sys.path.insert(0, str(COAT_SIDE))
    if payload is None:
        import CoatLinkInstall as installer
        payload = installer.read_payload()

    digest = hashlib.sha256(
        "".join("%s:%r" % (name, blob) for name, blob in sorted(payload["scripts"].items()))
        .encode("utf-8", "replace")).hexdigest()[:12]

    text = (source or SOURCE).read_text(encoding="utf-8")
    head, marker, tail = text.rpartition(GUARD)
    if not head or not marker:
        raise SystemExit("%s no longer ends with a main guard" % SOURCE)

    section = (EMBEDDED_SECTION
               .replace("__DIGEST__", digest)
               .replace("__SCRIPTS__", literal(payload["scripts"]))
               .replace("__ICONS__", literal(payload["icons"]))
               .replace("__TOOLS_XML__", repr(payload["tools_xml"])))

    output = Path(output) if output else ROOT / "dist" / "CoatLink-Setup.py"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(head + section + marker + tail, encoding="utf-8")
    return output, digest


def main():
    output, digest = build(sys.argv[1] if len(sys.argv) > 1 else None)
    print("%s  (payload %s)" % (output, digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
